#!/usr/bin/bash

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP --all &

# variables
scripts=~/.scripts

hyprpaper&
eww daemon
eww open resources
eww open leftbar
