#!/usr/bin/bash

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

fcitx5 -d
hyprpaper&
udiskie&
swaync&
eww open-many resources leftbar topbar
