window:
  dynamic_title: true
  dimensions:
    columns: 110
    lines: 25
  padding:
    x: 5
    y: 5

  opacity: 1.0
scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: MesloLGS NF
    style: Regular
  size: 9.0

env:
  TERM: xterm-256color

colors:
  # Default colors
  primary:
    background: '#1a1b26'
    foreground: '#c0caf5'

  # Normal colors
  normal:
    black:   '#15161e'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#a9b1d6'

  # Bright colors
  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#9ece6a'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'

  indexed_colors:
    - { index: 16, color: '#ff9e64' }
    - { index: 17, color: '#db4b4b' }
